load icu.maude .


fmod TEST is
    protecting ICU .
    protecting PATIENT .

    --- define env

    op testPatientOne : -> Patient .
    eq testPatientOne = patient(1, "John", 20) .

    op testPatientTwo : -> Patient .
    eq testPatientTwo = patient(2, "Jane", 25) .

    op testIcu1 : -> ICU .
    eq testIcu1 = icu("Psychiatric intensive care unit", pList(testPatientOne, pList)) .

    op testIcu2 : -> ICU .
    eq testIcu2 = icu("Trauma intensive care unit", pList(testPatientTwo, pList)) .

    op testIcus : -> ICUs .
    eq testIcus = icus(testIcu1, icus(testIcu2, icus)) .

    op testSensor1 : -> Sensor .
    eq testSensor1 = sensor(1, "Heart Rate Monitor", 50, 150) .

    op testSensor2 : -> Sensor .
    eq testSensor2 = sensor(2, "Blood Pressure Systolic", 120, 129) .

    op testSensor3 : -> Sensor .
    eq testSensor3 = sensor(3, "Blood Pressure Diastolic", 80, 84) .

    --- show usage
    --- get patient
    op getTestPatientOneName : -> PatientName .
    eq getTestPatientOneName = getName(testPatientOne) .
    --- get icu
    op getTestIcu1ByName : -> ICU .
    eq getTestIcu1ByName = getICU("Psychiatric intensive care unit", testIcus) .
    --- set sensor value
    op setTestSensor1Value : -> Sensor .
    eq setTestSensor1Value = setSensorValue( testSensor1, 100) . --- heart rate 100bpm


endfm